#!/bin/bash
#
# update script for openStat and instances
#
# if you start from a fresh "v1.0" installation, remember: 
#  copy color_css (vendor specific) to vendor/css in v1.0
#  ln -s v1.0 latest
#  sed -i 's/v1\.0/latest/g' /etc/apache2/sites-available/ntfnopsz-ssl.conf
#  crontab -e ...
#
USAGE='updateOS [--opsz] [--instance INSTANCENAME] [--webdir ABSOLUTEPATHTOWEBDIR]\n\n--webdir defaults to /var/www/html/openStat or /var/www/html/$INSTANCE.'
function php_no_error_reporting {
        cd "$WEBDIR"/latest
        _files=( public/html/index.php public/php/browseFileserver.php public/php/callFunction.php public/html/login.php public/html/changePassword.php )
        for _file in ${_files[@]}; do
                sed -i 's/\/\/error_reporting/error_reporting/' $_file
        done
        cd
}

# parse options
_opsz=false
WEBDIR=''
INSTANCE=''
while [[ "$@" != "" ]]; do
	case "$1" in
		"--instance")
			shift
			INSTANCE="$1"
			;;
		"--opsz")
			INSTANCE="openPSZ"
			;;
		"--webdir")
			shift
			WEBDIR="$1"
			;;
		"--help")
			echo -e "$USAGE"; exit 0;
			;;
		*) echo "Unknown option $1 (fatal)."; exit 1
			;;
	esac
	shift
done
if [[ "$INSTANCE" != "" ]]; then
	DEFAULTWEBDIR="/var/www/html/$INSTANCE";
else
	DEFAULTWEBDIR="/var/www/html/openStat";
fi
if [[ "$WEBDIR" == "" ]]; then WEBDIR="$DEFAULTWEBDIR"; fi
# get latest openStat release
REPO="openstat"
VERSION="$(curl --silent https://api.github.com/repos/codecivil/$REPO/releases/latest | grep 'tag_name' | sed 's/.*\": //;s/,//;s/\"//g' )" 
# make new dir if new version is available
mkdir "$WEBDIR/$VERSION" 2>/dev/null && {
	curl --silent "https://api.github.com/repos/codecivil/$REPO/releases/latest" | grep 'tarball_url' | sed 's/.*\": //;s/,//' | xargs wget -O openStat.tgz
	gunzip -c openStat.tgz | bzip2 -c - > openStat.tar.bz2
	#get and verify signature
	curl --silent "https://www2.codecivil.de/signatures/$REPO/$REPO-$VERSION.sig" --output "$REPO-$VERSION.sig"
	gpg --verify "$REPO-$VERSION.sig" openStat.tar.bz2 || { echo "Update cannot be verified."; rm openStat.tgz openStat.tar.bz2; rmdir "$WEBDIR/$VERSION"; exit 1; }
	rm openStat.tar.bz2
	# extract and install...
	mv openStat.tgz "$WEBDIR/$VERSION"
	cd "$WEBDIR/$VERSION"
	tar xzf openStat.tgz && {
		# renew license and readme
		cp codecivil-*/LICENSE "$WEBDIR/LICENSE.oStat"
		cp codecivil-*/README.md "$WEBDIR/README.oStat"
		# update this script
		cp codecivil-*/updateOS /usr/local/bin/
		# get correct files
		mv codecivil-*/nightly/* ./
		# reestablish customer specifics and plugins
		cp core/data/info.php  core/data/info.php.bkp
		cp -a "$WEBDIR/v1.0/core/data" "$WEBDIR/$VERSION/core/"
		mv core/data/info.php.bkp  core/data/info.php
		rm -r codecivil-*
		cp -a "$WEBDIR/v1.0/vendor/" "$WEBDIR/$VERSION/"
		cp -a "$WEBDIR/v1.0/vendor/css/" "$WEBDIR/$VERSION/public/"
		cp -a "$WEBDIR/v1.0/vendor/js/" "$WEBDIR/$VERSION/public/"
        # # update included plugins (note: there are no deletions! )
		cp -au "$WEBDIR/$VERSION/plugins/" "$WEBDIR/v1.0/"
        # # get full set of plugins in version folder
		cp -a "$WEBDIR/v1.0/plugins/" "$WEBDIR/$VERSION/"
		cp -a "$WEBDIR/$VERSION/plugins-config"/* "$WEBDIR/$VERSION/plugins/"
        #preserve settings.php (updates distribute settings.php.dist from now on)
        cp -a "$WEBDIR/latest/settings.php" "$WEBDIR/$VERSION/settings.php"
        #use package version of settings.php if none is present
        [[ -f "$WEBDIR/$VERSION/settings.php" ]] || cp -a "$WEBDIR/$VERSION/settings.php.dist" "$WEBDIR/$VERSION/settings.php"
		# cleanup
		rm "$WEBDIR/latest"
		ln -s "$WEBDIR/$VERSION" "$WEBDIR/latest"
		chown -R www-data:www-data "$WEBDIR/latest/"
	} && {
		echo "$(date): openStat updated to version $VERSION"
	}
	rm openStat.tgz
	php_no_error_reporting
}
cd
## continue if instance or opsz option is set
if [[ "$INSTANCE" == "" ]]; then exit 0; fi
# save openStat version
OS_VERSION="$VERSION"
# get latest $INSTANCE release
REPO="$INSTANCE"
. "$WEBDIR/$INSTANCE.version" || { read OPENSTAT_VERSION < "$WEBDIR/$INSTANCE.version"; INSTANCE_VERSION="$OPENSTAT_VERSION"; } #for smooth transition of $INSTANCE.version syntax
#make old version available
cp -a "$WEBDIR/$OPENSTAT_VERSION/$INSTANCE.tgz" "$WEBDIR/latest/"
#check for new version
VERSION="$(curl --silent https://api.github.com/repos/codecivil/$REPO/releases/latest | grep 'tag_name' | sed 's/.*\": //;s/,//;s/\"//g' )"
if [[ "$VERSION" != "$INSTANCE_VERSION" ]]; then
	curl --silent "https://api.github.com/repos/codecivil/$REPO/releases/latest" | grep 'tarball_url' | sed 's/.*\": //;s/,//' | xargs wget -O $INSTANCE.tgz
	gunzip -c $INSTANCE.tgz | bzip2 -c - > $INSTANCE.tar.bz2
	#get and verify signature of deterministic bzip2 file
	curl --silent "https://www2.codecivil.de/signatures/$REPO/$REPO-$VERSION.sig" --output "$REPO-$VERSION.sig"
	gpg --verify "$REPO-$VERSION.sig" $INSTANCE.tar.bz2 || { echo "Update for $REPO cannot be verified."; rm $INSTANCE.tgz $INSTANCE.tar.bz2; exit 1; }
	##
	rm $INSTANCE.tar.bz2
	mv $INSTANCE.tgz "$WEBDIR/latest/"
fi
# make new dir if new version is available
# extract and install...
cd "$WEBDIR/latest/"
tar xzf $INSTANCE.tgz && {
	# renew license and readme
	cp codecivil-*/LICENSE "$WEBDIR/LICENSE.opsz"
	cp codecivil-*/README.md "$WEBDIR/README.opsz"
	# update this script
	cp codecivil-*/updateOS /usr/local/bin/
	#
	cp -a codecivil-*/nightly/* ./
	cp core/data/info.php  core/data/info.php.bkp
	cp core/data/debugdata.php  core/data/debugdata.php.bkp
	cp settings.php  settings.php.bkp
	cp -a "$WEBDIR/v1.0/core/data" "$WEBDIR/latest/core/"
	mv core/data/info.php.bkp  core/data/info.php
	mv core/data/debugdata.php.bkp  core/data/debugdata.php
	mv settings.php.bkp  settings.php
	rm -r codecivil-*
	cp -a "$WEBDIR/v1.0/vendor/" "$WEBDIR/latest/"
	cp -a "$WEBDIR/v1.0/vendor/css/" "$WEBDIR/latest/public/"
	cp -a "$WEBDIR/v1.0/vendor/img/" "$WEBDIR/latest/public/"
	cp -a "$WEBDIR/v1.0/vendor/js/" "$WEBDIR/latest/public/"
    # # update included plugins (note: there are no deletions! )
    cp -au "$WEBDIR/latest/plugins/" "$WEBDIR/v1.0/"
    # # get full set of plugins in version folder
	cp -a "$WEBDIR/v1.0/plugins/" "$WEBDIR/latest/"
	cp -a "$WEBDIR/latest/plugins-config"/* "$WEBDIR/latest/plugins/"
	chown -R www-data:www-data "$WEBDIR/latest/"
} && {
	echo "$(date): $INSTANCE updated to version $VERSION"
	echo "INSTANCE_VERSION=$VERSION" > "$WEBDIR/$INSTANCE.version"
	echo "OPENSTAT_VERSION=$OS_VERSION" >> "$WEBDIR/$INSTANCE.version"
}
#rm $INSTANCE.tgz
php_no_error_reporting
cd

exit 0
